version: '3'
services:
  web:
    build: ../ImageProcess
    volumes:
      - ../ImageProcess:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    networks:
      - internal
    environment:
      - RABBITMQ_HOST=rabbitmq
      - BASE_URL=https://exuwomf4pougcn-3000.proxy.runpod.net
      - PYTHONUNBUFFERED=1

  websocket_client:
    build: ../WebSocket
    restart: always
    volumes:
      - ../WebSocket:/usr/src/app
    depends_on:
      - rabbitmq
    networks:
      - internal
    environment:
      - RABBITMQ_HOST=rabbitmq
      - WS_URL=ws://66.114.112.70:40563/ws?clientId=
    healthcheck:
      test: [ "CMD", "python", "-c", "import socket; socket.create_connection(('localhost', 40391))" ]
      interval: 30s
      timeout: 10s
      retries: 3


  rabbitmq:
    image: "rabbitmq:3-management"
    networks:
      - internal
networks:
  internal: